insert into Province select PRV_ID,PRV_LOCALNAME,PRV_ORDER_NUM,PRV_MEMO from NET_ABS_CN.dbo.RPROVINCE
insert into City select CTY_ID,CTY_LOCALNAME,CTY_PRV_ID,CTY_ORDER_NUM from NET_ABS_CN.dbo.RCITY
insert into Region select REG_ID,REG_LOCALNAME,REG_CTY_ID,REG_ORDER_NUM from NET_ABS_CN.dbo.RREGION